### ISSUE TITLE
Unable to scrape different flairs. Instead only scrapes single kind.

### ISSUE THREAD

**Issue by pranay-ar** [pranay-ar/Reddit-Flare-Detection#1]
When I try to extract the subreddit, r/India posts, I'm only able to extract one kind of flairs posts (all marked with AMA or AskIndia or something like that). I want a data set with posts belonging to different flairs. Can someone help me in this regard? The code is present in the Reddit Scraped Data Notebook.

**Comment by abhisheknaiidu** [comment]
Ahh, I see that you have used `PRAW` library, cool!

I guess its because of not using the flair class, after all It's not a method, it's a variable tho.
So instead of using this:
`topics_dict["flair"].append(flair)`

Try to use:
`topics_dict["flair"].append(submission.link_flair_text)`
I believe it will extract all the flairs related to particular sub-redit!

and haa just a suggestion, make sure to put ur credentials in a separate file lets say `praw.ini`
and put it in `.gitignore`

**Comment by pranay-ar** [comment]
Thanks bro! Gotta read the documentation of PRAW more carefully I guess :P
